### PR TITLE
Added custom label for selecting containers

### PR DESCRIPTION
**Pull request by Leny1996**
Regarding #13

### CODE REVIEW

**Review by jareware — APPROVED** [review]
Great, thanks!

**Comment by mnick86** [comment]
thanks for the change, this is what I was also looking for.

Do you know when you will push a new image to docker hub ? Thanks

**Comment by DecStobo** [comment]
Hi @jareware @Leny1996 ,

Thanks for your work on this ticket - Really useful to stop all of my containers/stacks going down when a backup is started!

When can we expect to see this in an upcoming version? Do you have a plan for v2.2.0? If not, can this be added to v2.1.1?

Cheers,
Declan.

**Comment by jareware** [comment]
This is now available as part of [the latest release](https://github.com/futurice/docker-volume-backup/releases/tag/v2.3.0)!

**Pull request merged**
