### PR TITLE
Fix timestamp and allow multiple instances

### PR DESCRIPTION
**Pull request by breuerfelix**
First of all, thank you @futurice, freaking awesome project ! this makes backing up docker volumes really easy :)

BUT ... There are some things that are really annoying:

- if you are running n docker compose projects and labeled some services with the shutdown flag, evertime any backup service does its backup, ALL containers are shut down, even the ones from other projects which are not even getting backed up in this run.
  - its the same for the hooks
- if you do 10 backups, all will be overwritten because the timestamp from the creation time of the service will be used as a backup name and not the actual timestamp of the backup
- you cant run shutdown with post and pre hooks because the services are going to get shutdown before the hooks will be executed, and started after the post hook will be executed

Changelog:

- you can provide a BACKUP_IDENT to the container. instead of passing `true` in the stop label, pass the IDENT now so only they will be shut down
  - if you don't change anything to your current setup, it wont behave differently :)
- fix backup names (now they have the correct timestamp
- start / stop will now run before / after the hooks so you can use both

TODO:

- same behaviour like start / stop for pre and post hooks
- switch to alpine image which reduce the image size alot
- update docs

### CODE REVIEW

**Comment by ipatalas** [comment]
This is great improvement! I am using this for my backups and noticed the same problems. Hope it will be merged soon.

**Comment by breuerfelix** [comment]
@ipatalas i have my master branch also pushed to docker hub because I noticed that I didn't receive any response and I really needed it for my work :) 

I got it here: https://hub.docker.com/r/felixbreuer/docker-volume-backup

i didnt change the readme for now but I will do this in the future aswell :) but it works really straight forward, just look at my changes and you will realise which changes you need to do :)

**Comment by ipatalas** [comment]
Yes yes yes! That's what I needed but didn't have time to do myself. Thanks for the info, will use it because it's pretty frustrating to have only one backup. Cheers!

**Comment by ipatalas** [comment]
After two days I finally have more backups! Thanks @breuerfelix

**Comment by Eslih** [comment]
As I prefer Alpine in production environments, I did fork your repo. Spend some time to make it somewhat more robust and implemented some best practices. Can be interesting if you want to implement some of my changes in your Ubuntu env. 

Planning to improve it further :-)

**Comment by breuerfelix** [comment]
@Eslih that sounds awesome !! could you make a pull request to my repo so i can review / merge your changes ? :)

**Pull request closed without merging**
